# Generated by Django 2.2.2 on 2019-06-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0001_initial'),
        ('disasterinfosite', '0002_data-load')
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='')),
            ],
        ),
    ]
