# Generated by Django 2.2.5 on 2019-09-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0003_surveycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='SurveyCode',
            name='dateEntered',
            field=models.DateField(null=True),
        ),
    ]
