FROM postgres:14.10-bookworm

# build postgres DB container image
RUN apt-get update && apt-get -y install \
    postgis                         \
    postgresql-14-postgis-3         \
    postgresql-14-postgis-3-scripts \
    && rm -rf /var/lib/apt/lists/*

USER postgres
