version: "3.3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:1.0.0
    ports:
      - "8888:80"
      - "8448:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  acme-companion:
    image: nginxproxy/acme-companion:2.2.0
    environment:
      DEFAULT_EMAIL: $DEFAULT_EMAIL
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
  seattle:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
        DATABASE_URL: $DATABASE_URL_SEATTLE
    depends_on:
    - postgres
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DATABASE_URL: $DATABASE_URL_SEATTLE
      VIRTUAL_HOST: $VIRTUAL_HOST
      VIRTUAL_PORT: 8001
      LETSENCRYPT_HOST: $VIRTUAL_HOST
      LETSENCRYPT_EMAIL: $DEFAULT_EMAIL
    image: ${TAG}:${VERSION}
    ports:
      - 8001:8000
    depends_on:
      - init
  portland:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
        DATABASE_URL: $DATABASE_URL_PORTLAND
    depends_on:
    - postgres
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DATABASE_URL: $DATABASE_URL_PORTLAND
      VIRTUAL_HOST: $VIRTUAL_HOST
      VIRTUAL_PORT: 8002
      LETSENCRYPT_HOST: $VIRTUAL_HOST
      LETSENCRYPT_EMAIL: $DEFAULT_EMAIL
    image: ${TAG}:${VERSION}
    ports:
      - 8002:8000
    depends_on:
      - init
  missoula:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
        DATABASE_URL: $DATABASE_URL_MISSOULA
    depends_on:
    - postgres
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DATABASE_URL: $DATABASE_URL_MISSOULA
      VIRTUAL_HOST: $VIRTUAL_HOST
      VIRTUAL_PORT: 8003
      LETSENCRYPT_HOST: $VIRTUAL_HOST
      LETSENCRYPT_EMAIL: $DEFAULT_EMAIL
    image: ${TAG}:${VERSION}
    ports:
      - 8003:8000
    depends_on:
      - init
  init:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
        DATABASE_URL: $DATABASE_URL
    depends_on:
    - postgres
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DATABASE_URL: $DATABASE_URL
    image: ${TAG}:${VERSION}
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    volumes:
    - postgres_db_data_volume_01:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
volumes:
  postgres_db_data_volume_01: {}
  certs: {}
  vhost: {}
  html: {}
  acme: {}
