version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:1.0.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - proxy
  acme-companion:
    image: nginxproxy/acme-companion:2.2.0
    environment:
      DEFAULT_EMAIL: $DEFAULT_EMAIL
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    restart: always
    depends_on:
      - nginx-proxy
  seattle:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
        DATABASE_URL: $DATABASE_URL_SEATTLE
    restart: always
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DATABASE_URL: $DATABASE_URL_SEATTLE
      VIRTUAL_HOST: $VIRTUAL_HOST
      VIRTUAL_PORT: 8000
      VIRTUAL_PATH: $VIRTUAL_PATH_SEATTLE
      LETSENCRYPT_HOST: $VIRTUAL_HOST
      LETSENCRYPT_EMAIL: $DEFAULT_EMAIL
    image: ${TAG}:${VERSION}
    expose:
      - 80
    depends_on:
      - init
      - postgres
  portland:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
        DATABASE_URL: $DATABASE_URL_PORTLAND
    restart: always
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DATABASE_URL: $DATABASE_URL_PORTLAND
      VIRTUAL_HOST: $VIRTUAL_HOST
      VIRTUAL_PORT: 8000
      VIRTUAL_PATH: $VIRTUAL_PATH_PORTLAND
      LETSENCRYPT_HOST: $VIRTUAL_HOST
      LETSENCRYPT_EMAIL: $DEFAULT_EMAIL
    image: ${TAG}:${VERSION}
    expose:
      - 80
    depends_on:
      - init
      - postgres
  missoula:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
        DATABASE_URL: $DATABASE_URL_MISSOULA
    restart: always
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DATABASE_URL: $DATABASE_URL_MISSOULA
      VIRTUAL_HOST: $VIRTUAL_HOST
      VIRTUAL_PORT: 8000
      VIRTUAL_PATH: $VIRTUAL_PATH_MISSOULA
      LETSENCRYPT_HOST: $VIRTUAL_HOST
      LETSENCRYPT_EMAIL: $DEFAULT_EMAIL
    image: ${TAG}:${VERSION}
    expose:
      - 80
    depends_on:
      - init
      - postgres
  init:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
        DATABASE_URL: $DATABASE_URL
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DATABASE_URL: $DATABASE_URL
    image: ${TAG}:${VERSION}
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    image: hazardready-postgres:${VERSION}
    volumes:
    - postgres_db_data_volume_01:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

volumes:
  postgres_db_data_volume_01: {}
  certs: {}
  vhost: {}
  html: {}
  acme: {}

networks:
  proxy:
    external:
      name: nginx-proxy

